EOF

# Initialize and validate Terraform configuration
(cd /home/node/terraform-validate && terraform init && terraform validate)

# If it passes validation, let the user know
echo <<'EOF'
{
  "files": {
    "main.tf": "terraform {\nrequired_providers {\nazurerm = {\nsource  = \"hashicorp/azurerm\"\nversion = \"~> 4.56.0\"\n }\n}\n}\n\nprovider \"azurerm\" {\nfeatures {}\n}\n\nresource \"azurerm_resource_group\" \"rg\" {\nname     = var.resource_group_name\nlocation = var.location\n}\n\nresource \"azurerm_app_service_plan\" \"asp\" {\nname                = \"appserviceplan\"\nlocation            = azurerm_resource_group.rg.location\nresource_group_name = azurerm_resource_group.rg.name\nsku {\ntier = \"Standard\"\nsize = \"S1\"\n}\n}\n\nresource \"azurerm_app_service\" \"webapp\" {\nname                = \"webapp\"\nlocation            = azurerm_resource_group.rg.location\nresource_group_name = azurerm_resource_group.rg.name\napp_service_plan_id = azurerm_app_service_plan.asp.id\nsite_config {\nalways_on = true\n}\n}\n\nresource \"azurerm_sql_server\" \"sqlserver\" {\nname                = \"sqlserver\"\nresource_group_name = azurerm_resource_group.rg.name\nlocation            = azurerm_resource_group.rg.location\nversion             = \"12.0\"\nadministrator_login = var.sql_admin_username\nadministrator_login_password = var.sql_admin_password\n}\n\nresource \"azurerm_sql_database\" \"sqldb\" {\nname                = \"sqldb\"\nresource_group_name = azurerm_sql_server.sqlserver.resource_group_name\nlocation            = azurerm_sql_server.sqlserver.location\nserver_name         = azurerm_sql_server.sqlserver.name\nrequested_service_objective_name = \"S0\"\n}\n\nresource \"azurerm_api_management\" \"apim\" {\nname                = \"apimservice\"\nlocation            = azurerm_resource_group.rg.location\nresource_group_name = azurerm_resource_group.rg.name\npublisher_name      = \"company\"\npublisher_email     = \"company@example.com\"\nsku_name            = \"Developer_1\"\n}\n\nresource \"azurerm_application_insights\" \"appinsights\" {\nname                = \"appinsights\"\nlocation            = azurerm_resource_group.rg.location\nresource_group_name = azurerm_resource_group.rg.name\napplication_type    = \"web\"\n}\n\nresource \"azurerm_virtual_network\" \"vnet\" {\nname                = \"vnet\"\naddress_space       = [\"10.0.0.0/16\"]\nlocation            = azurerm_resource_group.rg.location\nresource_group_name = azurerm_resource_group.rg.name\n}\n\nresource \"azurerm_subnet\" \"subnet\" {\nname                 = \"subnet1\"\nresource_group_name  = azurerm_resource_group.rg.name\nvirtual_network_name = azurerm_virtual_network.vnet.name\naddress_prefixes     = [\"10.0.1.0/24\"]\n}\n\nresource \"azurerm_network_security_group\" \"nsg\" {\nname                = \"nsg\"\nlocation            = azurerm_resource_group.rg.location\nresource_group_name = azurerm_resource_group.rg.name\n}\n",
    "variables.tf": "variable \"resource_group_name\" {\ndescription = \"The name of the resource group\"\ntype        = string\n}\n\nvariable \"location\" {\ndescription = \"The location of the resource group\"\ntype        = string\n}\n\nvariable \"sql_admin_username\" {\ndescription = \"The SQL server administrator username\"\ntype        = string\n}\n\nvariable \"sql_admin_password\" {\ndescription = \"The SQL server administrator password\"\ntype        = string\nsensitive   = true\n}\n",
    "terraform.tfvars": "resource_group_name = \"rg-banking-portal\"\nlocation            = \"East US\"\nsql_admin_username  = \"sqladmin\"\nsql_admin_password  = \"P@ssw0rd!\"\n",
    "backend.tf": ""
  }
}