resource_group_name = "my-resource-group"
location          = "West Europe"
app_service_plan_id = "example-plan-id"
sql_admin_login    = "example_sql_admin"
sql_admin_password = "example_password"
role_principal_id  = "example-principal-id"
