location = "East US"
resource_group_name = "example-resources"
app_service_plan_name = "example-appserviceplan"
app_service_name = "example-appservice"
function_app_name = "example-functionapp"
storage_account_name = "examplestorageacc"