azure_location = "East US"
azure_rg = "example-resources"
aws_region = "us-east-1"
google_project = "my-gcp-project"
google_region = "us-central1"
log_analytics_workspace_id = "<workspace_id>"
principal_id = "<principal_id>"
